# Generated by Django 2.2.9 on 2020-01-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200127_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='_text_rendered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_markup_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
